- name: Creating cart server
  hosts: all
  become: yes
  tasks:
    - name: Downloading Nodejs Repo
      ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

    - name: Installing nodejs Server
      ansible.builtin.yum:
        name: nodejs
        state: latest

    - name: Adding User
      ansible.builtin.user:
        name: roboshop

    - name: Remove the Directory
      ansible.builtin.file:
        path: /app
        state: absent

    - name: Create a directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: Downloading new app content
      ansible.builtin.unarchive:
        src: https://roboshop-artifacts.s3.amazonaws.com/cart.zip
        dest: /app
        remote_src: yes

    - name: Installing NodeJs Dependencies
      ansible.builtin.shell: npm install
      args:
        chdir: /app


    - name: Copying Service File and starting the service
      ansible.builtin.copy:
        src: catalogue.service
        dest: /etc/systemd/system/cart.service

    - name: Enabling and restarting cart Server
      ansible.builtin.systemd:
        state: restarted
        name: cart
        enabled: true
        daemon_reload: true

